import '@geist-ui/react/dist/geist-ui.css';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ fontFamily: 'Geist, Geist Mono, Arial, sans-serif' }}
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
